apiVersion: apps/v1
kind: Deployment
metadata:
  name: srams-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srams-frontend
  template:
    metadata:
      labels:
        app: srams-frontend
    spec:
      containers:
      - name: srams-frontend
        image: ghcr.io/p3-hype/srams-frontend:v1.2.3
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github-container-registry
