apiVersion: v1
kind: Service
metadata:
  name: srams-frontend-service
spec:
  selector:
    app: srams-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31355
  type: NodePort
